# Generated by Django 4.0.2 on 2022-10-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patregtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(max_length=3)),
                ('email', models.CharField(max_length=50)),
                ('phoneno', models.IntegerField(max_length=10)),
                ('address', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
